services:
  - type: web
    name: bella-bot-v2
    env: docker
    plan: free
    branch: main
    autoDeploy: false
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: VITE_DISCORD_CLIENT_ID
        sync: false
      - key: VITE_DISCORD_CLIENT_SECRET
        sync: false
      - key: VITE_DISCORD_REDIRECT_URI
        sync: false
      - key: VITE_API_ALLOW_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: POLLINATIONS_TOKEN
        sync: false
